name:                rl-gen
version:             0.1.0.0
github:              "githubuser/rl-gen"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rl-gen#readme>

dependencies:
- base >= 4.7 && < 5
- random
- data-default
- containers
- lens
- deepseq
- mtl
- QuickCheck-GenT
- QuickCheck

ghc-options:
  - -Wall
  - -Werror

library:
  source-dirs: src

executables:
  rl-gen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rl-gen

tests:
  rl-gen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rl-gen
